# This workflow will install Python dependencies, run tests and lint with a single version of Python using nox
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: lint and test

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        python: ["3.12"]


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run ruff
        run: |
          uv add ruff --dev
          uv run ruff format tests
          uv run ruff check tests
      - name: Run Test and code cov
        run: |
            uv run pytest
